#ifndef LUNARML_OPCODE_H
#define LUNARML_OPCODE_H

enum Opcode {
    OP_RETURN = 0,
    OP_PUSH_EMPTY,
    OP_PUSH_UNIT,
    OP_PUSH_NIL,
    OP_PUSH_FALSE,
    OP_PUSH_TRUE,
    OP_PUSH_CONST,
    OP_PUSH_FREE,
    OP_POP,
    OP_POP_AND_SET,
    OP_COPY_AND_PUSH,
    OP_CALL,
    OP_TAILCALL,
    OP_PRIMCALL,
    OP_MAKE_TUPLE,
    OP_PROJECT,
    OP_MAKE_CLOSURE,
    OP_UPDATE_CLOSURE,
    OP_MAKE_LIST,
    OP_MAKE_VECTOR,
    OP_CONS,
    OP_MAKE_DATA_WITHOUT_PAYLOAD,
    OP_MAKE_DATA_WITH_PAYLOAD,
    OP_DATA_TAG,
    OP_DATA_PAYLOAD,
    OP_MAKE_EXCEPTION_WITHOUT_PAYLOAD,
    OP_MAKE_EXCEPTION_WITH_PAYLOAD,
    OP_EXCEPTION_PAYLOAD,
    OP_JUMP,
    OP_JUMP_IF_TRUE,
    OP_PUSH_EXCEPTION_HANDLER,
    OP_POP_EXCEPTION_HANDLER,
    OP_RAISE
};

#endif
