val _ = "foo" : String32.string;
val _ = #"x" : String32.char;
val _ = String32.size : String32.string -> int;
val 0 = String32.size "";
val 3 = String32.size "foo";
val _ = String32.sub : String32.string * int -> Char32.char;
val #"f" = String32.sub ("foo", 0);
val #"o" = String32.sub ("foo", 1);
val #"o" = String32.sub ("foo", 2);
val #"\u3042" = String32.sub ("\u3042\u{1D400}", 0);
val #"\U0001D400" = String32.sub ("\u3042\u{1D400}", 1);
(String32.sub ("\u3042\u{1D400}", ~1); print "Bad\n") handle Subscript => print "Good\n";
(String32.sub ("\u3042\u{1D400}", 2); print "Bad\n") handle Subscript => print "Good\n";
val _ = String32.^ : String32.string * String32.string -> String32.string;
print (String32.toString (String32.^ ("Hello ", "world!")) ^ "\n");
val _ = String32.concat : String32.string list -> String32.string;
print (String32.toString (String32.concat ["Standard ", "ML"]) ^ "\n");
val _ = String32.concatWith : String32.string -> String32.string list -> String32.string;
print (String32.toString (String32.concatWith "," ("foo" :: "bar" :: "baz" :: nil)) ^ "\n");
val _ = String32.str : Char32.char -> String32.string;
print (String32.toString (String32.str #"\u3042") ^ "\n");
val _ = String32.implode : Char32.char list -> String32.string;
print (String32.toString (String32.implode [#"i", #"m", #"p", #"l", #"o", #"d", #"e", #"\uD83D", #"\uDE00", #"\U0001FFFF"]) ^ "\n");
val _ = String32.explode : String32.string -> Char32.char list;
print (String32.toString (String32.concatWith "." (List.map String32.str (String32.explode "xyz\u3042"))) ^ "\n");
val _ = String32.map : (Char32.char -> Char32.char) -> String32.string -> String32.string;
print (String32.toString (String32.map (fn #"e" => #"3" | #"l" => #"1" | #"o" => #"0" | x => x) "Hello world!") ^ "\n");
val _ = String32.translate : (Char32.char -> String32.string) -> String32.string -> String32.string;
print (String32.toString (String32.translate (fn #"H" => "|-|" | #"e" => "3" | #"l" => "|" | #"w" => "vv" | x => String32.str x) "Hello world!") ^ "\n");
