return "LanguageOptionsRecord", {
  -- "allowDoDecls",
  "allowExtendedNumConsts",
  "allowExtendedTextConsts",
  -- "allowLineComments",
  -- "allowOptBar",
  -- "allowOptSemicolon",
  -- "allowOrPats",
  -- "allowRecordPunExps",
  "allowSigWithtype",
  "allowVectorExps",
  "allowVectorPats",
  -- "allowPatternGuards",
  -- "allowConjunctivePats",
  -- "allowNestedMatches",
  "allowRecordExtension",
  "allowRecordUpdate",
  "allowUtfEscapeSequences",
  "allowHexFloatConsts",
  "allowValRecTyVars",
  "allowValTyVarsRec",
  "allowFreeTyVarsInDatatypeDec",
  "allowWhereAndType",
  "allowPrim",
  "allowBindEqual",
  "allowOverload",
  "allowInfixingDot",
  "allowSignatureComment",
  "nonexhaustiveBind",
  "nonexhaustiveMatch",
  "nonexhaustiveRaise",
  "redundantBind",
  "redundantMatch",
  "redundantRaise",
}
