on: [push, pull_request]
name: build-docs
jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
