on: [push, pull_request]
name: build-docs
jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
          working-directory: 'docs/'
      - name: Sync dependencies
        run: rye sync
        working-directory: ./docs
      - name: Build HTML
        run: make -C docs SPHINXBUILD="rye run sphinx-build" html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
